#include "amiga_http.h"
#include "amiga_tls.h"
#include "amigpt/httpdec.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
typedef struct {amigpt_http_response *r;} collect_ctx;
static void collect(const char*d,size_t n,void*u){collect_ctx *cc=(collect_ctx*)u;amigpt_http_response*r=cc->r;if(!n||r->oom)return;if(r->len+n+1>r->cap){size_t nc=r->cap?r->cap*2:4096;char*p;while(nc<r->len+n+1){if(nc>1024UL*1024UL*8UL){r->oom=1;return;}nc*=2;}p=(char*)realloc(r->body,nc);if(!p){r->oom=1;return;}r->body=p;r->cap=nc;}memcpy(r->body+r->len,d,n);r->len+=n;r->body[r->len]=0;}
void amigpt_http_response_free(amigpt_http_response*r){if(!r)return;free(r->body);memset(r,0,sizeof *r);}
static int run_request(const char*host,const char *head,const char *body,size_t bodylen,amigpt_http_response*out,char*err,size_t errcap){amigpt_tls*t;amigpt_httpdec h;static char buf[4096];int n,rc;collect_ctx cc;memset(out,0,sizeof *out);cc.r=out;t=amigpt_tls_connect(host,443,err,errcap);if(!t)return -1;if(amigpt_tls_write_all(t,head,strlen(head),err,errcap)<0 || (bodylen&&amigpt_tls_write_all(t,body,bodylen,err,errcap)<0)){amigpt_tls_close(t);return -1;}amigpt_httpdec_init(&h);while((n=amigpt_tls_read(t,buf,sizeof buf,err,errcap))>0){rc=amigpt_httpdec_feed(&h,buf,(size_t)n,collect,&cc);if(rc<0||out->oom){if(out->oom)snprintf(err,errcap,"HTTP response out of memory");amigpt_tls_close(t);amigpt_http_response_free(out);return -1;}}out->status=h.status;amigpt_tls_close(t);if(n<0){amigpt_http_response_free(out);return -1;}if(!out->body){out->body=(char*)calloc(1,1);if(!out->body){snprintf(err,errcap,"out of memory");return -1;}out->cap=1;}return 0;}
int amigpt_https_get(const char*host,const char*path,const char*accept,amigpt_http_response*out,char*err,size_t errcap){static char hdr[2048];int hn;if(!accept)accept="application/json";hn=snprintf(hdr,sizeof hdr,"GET %s HTTP/1.1\r\nHost: %s\r\nAccept: %s\r\nConnection: close\r\n\r\n",path,host,accept);if(hn<0||(size_t)hn>=sizeof hdr){snprintf(err,errcap,"HTTP header too large");return -1;}return run_request(host,hdr,0,0,out,err,errcap);}
int amigpt_https_get_bearer(const char*host,const char*path,const char*accept,const char*token,amigpt_http_response*out,char*err,size_t errcap){char *hdr;size_t cap;int hn,rc;if(!accept)accept="application/json";if(!token||!*token){snprintf(err,errcap,"missing bearer token");return -1;}cap=strlen(token)+strlen(host)+strlen(path)+strlen(accept)+256;hdr=(char*)malloc(cap);if(!hdr){snprintf(err,errcap,"out of memory");return -1;}hn=snprintf(hdr,cap,"GET %s HTTP/1.1\r\nHost: %s\r\nAuthorization: Bearer %s\r\nAccept: %s\r\nConnection: close\r\n\r\n",path,host,token,accept);if(hn<0||(size_t)hn>=cap){free(hdr);snprintf(err,errcap,"HTTP header too large");return -1;}rc=run_request(host,hdr,0,0,out,err,errcap);free(hdr);return rc;}
int amigpt_https_post_form(const char*host,const char*path,const char*form,amigpt_http_response*out,char*err,size_t errcap){static char hdr[2048];int hn;size_t flen=strlen(form);hn=snprintf(hdr,sizeof hdr,"POST %s HTTP/1.1\r\nHost: %s\r\nContent-Type: application/x-www-form-urlencoded\r\nAccept: application/json\r\nConnection: close\r\nContent-Length: %lu\r\n\r\n",path,host,(unsigned long)flen);if(hn<0||(size_t)hn>=sizeof hdr){snprintf(err,errcap,"HTTP header too large");return -1;}return run_request(host,hdr,form,flen,out,err,errcap);}
int amigpt_https_post_json(const char*host,const char*path,const char*json,amigpt_http_response*out,char*err,size_t errcap){static char hdr[2048];int hn;size_t len=strlen(json);hn=snprintf(hdr,sizeof hdr,"POST %s HTTP/1.1\r\nHost: %s\r\nContent-Type: application/json\r\nAccept: application/json\r\nConnection: close\r\nContent-Length: %lu\r\n\r\n",path,host,(unsigned long)len);if(hn<0||(size_t)hn>=sizeof hdr){snprintf(err,errcap,"HTTP header too large");return -1;}return run_request(host,hdr,json,len,out,err,errcap);}
