#include "device_auth.h"
#include "amiga_http.h"
#include "idtoken_verify.h"
#include "amigpt/jsonlite.h"
#include "amigpt/jwt.h"
#include <proto/dos.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { char device_auth_id[1024]; char user_code[256]; unsigned long interval; } device_code;

static int parse_interval(const char *json,unsigned long *out){char s[64];long n=0;int rc=amigpt_json_string(json,"interval",s,sizeof s);if(rc==1){char *end=0;unsigned long v=strtoul(s,&end,10);if(!end||*end||v==0||v>300)return -1;*out=v;return 0;}rc=amigpt_json_long(json,"interval",&n);if(rc==1&&n>0&&n<=300){*out=(unsigned long)n;return 0;}return -1;}
static int request_code(device_code *dc,char *err,size_t errcap){amigpt_http_response r;char body[512];int n;memset(dc,0,sizeof *dc);n=snprintf(body,sizeof body,"{\"client_id\":\"%s\"}",AMIGPT_CODEX_CLIENT_ID);if(n<0||(size_t)n>=sizeof body){snprintf(err,errcap,"device auth request too large");return -1;}if(amigpt_https_post_json("auth.openai.com","/api/accounts/deviceauth/usercode",body,&r,err,errcap)<0)return -1;if(r.status<200||r.status>=300){snprintf(err,errcap,"device auth start HTTP %d",r.status);amigpt_http_response_free(&r);return -1;}if(amigpt_json_string(r.body,"device_auth_id",dc->device_auth_id,sizeof dc->device_auth_id)!=1||amigpt_json_string(r.body,"user_code",dc->user_code,sizeof dc->user_code)!=1||parse_interval(r.body,&dc->interval)<0){snprintf(err,errcap,"invalid device auth response");amigpt_http_response_free(&r);return -1;}amigpt_http_response_free(&r);return 0;}
static int poll_code(const device_code *dc,char *auth_code,size_t codecap,char *verifier,size_t vcap,char *err,size_t errcap){static char body[2048],challenge[512];amigpt_http_response r;int n;unsigned long waited=0;n=snprintf(body,sizeof body,"{\"device_auth_id\":\"%s\",\"user_code\":\"%s\"}",dc->device_auth_id,dc->user_code);if(n<0||(size_t)n>=sizeof body){snprintf(err,errcap,"device poll request too large");return -1;}while(waited<900){if(amigpt_https_post_json("auth.openai.com","/api/accounts/deviceauth/token",body,&r,err,errcap)<0)return -1;if(r.status>=200&&r.status<300){if(amigpt_json_string(r.body,"authorization_code",auth_code,codecap)!=1||amigpt_json_string(r.body,"code_verifier",verifier,vcap)!=1||amigpt_json_string(r.body,"code_challenge",challenge,sizeof challenge)!=1){snprintf(err,errcap,"invalid device token response");amigpt_http_response_free(&r);return -1;}amigpt_http_response_free(&r);return 0;}if(r.status!=403&&r.status!=404){snprintf(err,errcap,"device auth poll HTTP %d",r.status);amigpt_http_response_free(&r);return -1;}amigpt_http_response_free(&r);Delay((ULONG)(dc->interval*50UL));waited+=dc->interval;}snprintf(err,errcap,"device auth timed out after 15 minutes");return -1;}
static int extract_claim(const char *jwt,const char *key,char *out,size_t cap){static char h[2048],p[16384];if(amigpt_jwt_decode_parts(jwt,h,sizeof h,p,sizeof p,0)<0)return -1;return amigpt_json_string(p,key,out,cap)==1?0:-1;}
int amigpt_device_login(amigpt_tokens *tokens,char *account_id,size_t account_cap,char *email,size_t email_cap,char *err,size_t errcap){static device_code dc;static char code[4096],verifier[1024];if(!tokens||!account_id||account_cap<2||!email||email_cap<2){snprintf(err,errcap,"device login arguments missing");return -1;}account_id[0]=0;email[0]=0;if(request_code(&dc,err,errcap)<0)return -1;puts("Open this address on a browser and sign in:");puts(AMIGPT_DEVICE_VERIFY_URL);printf("One-time code: %s\n",dc.user_code);printf("Waiting for authorization (expires in 15 minutes)...\n");if(poll_code(&dc,code,sizeof code,verifier,sizeof verifier,err,errcap)<0)return -1;if(amigpt_exchange_device_code(AMIGPT_CODEX_CLIENT_ID,code,verifier,"https://auth.openai.com/deviceauth/callback",tokens,err,errcap)<0)return -1;if(extract_claim(tokens->id_token,"chatgpt_account_id",account_id,account_cap)<0){snprintf(err,errcap,"ID token has no chatgpt_account_id");return -1;}(void)extract_claim(tokens->id_token,"email",email,email_cap);return 0;}
