#include <dos/dostags.h>
/* OAuth controller. Browser is a separate native AmiWebAuth process. */
#include <dos/dos.h>
#include <proto/dos.h>
#include <string.h>
#include <stdio.h>
#include "amigpt/oauth.h"
#include "amigpt/pkce.h"
#include "amigpt/profile.h"
#include "amigpt/scope.h"
#include "amiga_crypto.h"
#include "oauth_loopback.h"
#include "oauth_exchange.h"
#include "idtoken_verify.h"
#include "login_flow.h"
static int launch_browser(const char *url){static char cmd[8192];if(snprintf(cmd,sizeof cmd,"PROGDIR:AmiWebAuth \"%s\"",url)<0)return -1;return SystemTags((STRPTR)cmd,SYS_Asynch,TRUE,TAG_DONE)==-1?-1:0;}
int amigpt_browser_login(const amigpt_profile *existing,amigpt_tokens *tokens,amigpt_identity *identity,char *issued_client,size_t clientcap,char *err,size_t errcap){int ls=-1,rc=-1;unsigned short port;static char redirect[256],verifier[128],challenge[128],state[128],nonce[128],url[8192];static amigpt_callback cb;amigpt_oauth_params p;const int returning=existing&&!strncmp(existing->client_id,"oaiapp_",7);const char *client_id=returning?existing->client_id:AMIGPT_DYNAMIC_CLIENT;if(!existing||!existing->host_id[0]){snprintf(err,errcap,"missing host_id");return -1;}if(!tokens||!issued_client||clientcap==0){snprintf(err,errcap,"login arguments missing");return -1;}if(!amigpt_crypto_is_open()){snprintf(err,errcap,"network/AmiSSL runtime not initialized");return -1;}if(amigpt_make_verifier(verifier,sizeof verifier)<0||amigpt_make_nonce(state,sizeof state)<0||amigpt_make_nonce(nonce,sizeof nonce)<0||amigpt_pkce_challenge(verifier,amigpt_amiga_sha256,challenge,sizeof challenge)<0){snprintf(err,errcap,"secure random/PKCE failed");return -1;}ls=amigpt_loopback_open(&port,err,errcap);if(ls<0)return -1;snprintf(redirect,sizeof redirect,"http://127.0.0.1:%u/auth/callback",(unsigned)port);memset(&p,0,sizeof p);p.client_id=client_id;p.host_id=existing->host_id;p.agent_name=returning?0:"AmiGPT68K";p.redirect_uri=redirect;p.state=state;p.nonce=nonce;p.challenge=challenge;p.id_token_hint=returning&&existing->id_token[0]?existing->id_token:0;p.login_hint=returning&&existing->email[0]?existing->email:0;if(amigpt_oauth_authorize_url(&p,url,sizeof url)<0){snprintf(err,errcap,"authorization URL too large");goto out_listener;}if(launch_browser(url)<0){snprintf(err,errcap,"cannot launch AmiWebAuth");goto out_listener;}if(amigpt_loopback_wait(ls,&cb,600,err,errcap)<0)goto out_listener;if(cb.error[0]){snprintf(err,errcap,"OAuth error: %s",cb.error);goto out_listener;}if(strcmp(cb.state,state)!=0){snprintf(err,errcap,"OAuth state mismatch");goto out_listener;}if(returning){if(cb.client_id[0]&&strcmp(cb.client_id,existing->client_id)!=0){snprintf(err,errcap,"OAuth client_id changed unexpectedly");goto out_listener;}snprintf(issued_client,clientcap,"%s",existing->client_id);}else{if(!cb.client_id[0]){snprintf(err,errcap,"OpenAI did not return issued client_id");goto out_listener;}snprintf(issued_client,clientcap,"%s",cb.client_id);}if(amigpt_exchange_code(issued_client,cb.code,verifier,redirect,tokens,err,errcap)<0)goto out_listener;if(!amigpt_scope_has(tokens->scope,"chatgpt.tokens.use.direct")){snprintf(err,errcap,"ChatGPT plan permission was not granted");goto out_listener;}if(identity&&amigpt_verify_id_token(tokens->id_token,issued_client,nonce,identity,err,errcap)<0)goto out_listener;rc=0;out_listener:if(ls>=0)amigpt_loopback_close(ls);return rc;}
int amigpt_first_login(const char *host_id,amigpt_tokens *tokens,char *issued_client,size_t clientcap,char *err,size_t errcap){static amigpt_profile p;amigpt_profile_init(&p);if(!host_id||!*host_id){snprintf(err,errcap,"missing host_id");return -1;}snprintf(p.host_id,sizeof p.host_id,"%s",host_id);return amigpt_browser_login(&p,tokens,0,issued_client,clientcap,err,errcap);}
