#include "oauth_exchange.h"
#include "amiga_http.h"
#include "amigpt/oauth.h"
#include "amigpt/urlcodec.h"
#include "amigpt/jsonlite.h"
#include <string.h>
#include <stdio.h>
static int parse(amigpt_http_response*r,amigpt_tokens*t,char*err,size_t cap){char e[256];memset(t,0,sizeof *t);if(r->status<200||r->status>=300){if(amigpt_json_string(r->body,"error",e,sizeof e)!=1){if(amigpt_json_string(r->body,"error_description",e,sizeof e)!=1)snprintf(e,sizeof e,"HTTP %d",r->status);}snprintf(err,cap,"token endpoint: %s",e);return -1;}if(amigpt_json_string(r->body,"access_token",t->access_token,sizeof t->access_token)!=1){snprintf(err,cap,"token response has no access_token");return -1;}if(amigpt_json_string(r->body,"id_token",t->id_token,sizeof t->id_token)!=1){snprintf(err,cap,"token response has no id_token");return -1;}amigpt_json_string(r->body,"refresh_token",t->refresh_token,sizeof t->refresh_token);amigpt_json_string(r->body,"scope",t->scope,sizeof t->scope);amigpt_json_long(r->body,"expires_in",&t->expires_in);amigpt_json_long(r->body,"earliest_refresh_at",&t->earliest_refresh_at);return 0;}
int amigpt_exchange_code(const char*ci,const char*code,const char*ver,const char*ru,amigpt_tokens*t,char*err,size_t cap){static char form[16384];amigpt_http_response r;int rc;if(amigpt_oauth_code_form(ci,code,ver,ru,form,sizeof form)<0){snprintf(err,cap,"token form too large");return -1;}if(amigpt_https_post_form("auth.openai.com","/api/accounts/oauth/token",form,&r,err,cap)<0)return -1;rc=parse(&r,t,err,cap);amigpt_http_response_free(&r);return rc;}
int amigpt_exchange_device_code(const char*ci,const char*code,const char*ver,const char*ru,amigpt_tokens*t,char*err,size_t cap){static char a[512],b[8192],c[2048],d[1024],form[16384];amigpt_http_response r;int n,rc;if(amigpt_urlencode(ci,a,sizeof a)<0||amigpt_urlencode(code,b,sizeof b)<0||amigpt_urlencode(ver,c,sizeof c)<0||amigpt_urlencode(ru,d,sizeof d)<0){snprintf(err,cap,"token form encoding failed");return -1;}n=snprintf(form,sizeof form,"grant_type=authorization_code&client_id=%s&code=%s&redirect_uri=%s&code_verifier=%s",a,b,d,c);if(n<0||(size_t)n>=sizeof form){snprintf(err,cap,"token form too large");return -1;}if(amigpt_https_post_form("auth.openai.com","/oauth/token",form,&r,err,cap)<0)return -1;rc=parse(&r,t,err,cap);amigpt_http_response_free(&r);return rc;}
int amigpt_refresh_tokens(const char*ci,const char*rt,amigpt_tokens*t,char*err,size_t cap){static char form[16384];amigpt_http_response r;int rc;if(amigpt_oauth_refresh_form(ci,rt,form,sizeof form)<0){snprintf(err,cap,"refresh form too large");return -1;}if(amigpt_https_post_form("auth.openai.com","/api/accounts/oauth/token",form,&r,err,cap)<0)return -1;rc=parse(&r,t,err,cap);amigpt_http_response_free(&r);return rc;}
int amigpt_refresh_device_tokens(const char*ci,const char*rt,amigpt_tokens*t,char*err,size_t cap){static char esc_ci[512],esc_rt[12288],json[16384];amigpt_http_response r;int n,rc;if(strchr(ci,'"')||strchr(ci,'\\')||strchr(rt,'"')||strchr(rt,'\\')){snprintf(err,cap,"invalid refresh token/client id");return -1;}snprintf(esc_ci,sizeof esc_ci,"%s",ci);snprintf(esc_rt,sizeof esc_rt,"%s",rt);n=snprintf(json,sizeof json,"{\"grant_type\":\"refresh_token\",\"client_id\":\"%s\",\"refresh_token\":\"%s\"}",esc_ci,esc_rt);if(n<0||(size_t)n>=sizeof json){snprintf(err,cap,"refresh JSON too large");return -1;}if(amigpt_https_post_json("auth.openai.com","/oauth/token",json,&r,err,cap)<0)return -1;rc=parse(&r,t,err,cap);amigpt_http_response_free(&r);return rc;}
