#include "session.h"
#include "login_flow.h"
#include "device_auth.h"
#include "oauth_exchange.h"
#include "idtoken_verify.h"
#include "amiga_crypto.h"
#include "amigpt/profile.h"
#include "amigpt/scope.h"
#include "amigpt/jwt.h"
#include "amigpt/jsonlite.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
static int ensure_host_id(amigpt_profile *p,char *err,size_t errcap){if(p->host_id[0])return 0;if(!amigpt_crypto_is_open()){snprintf(err,errcap,"network/AmiSSL runtime not initialized");return -1;}if(amigpt_make_uuid_urn(p->host_id,sizeof p->host_id)<0){snprintf(err,errcap,"cannot create host id");return -1;}return 0;}
int amigpt_session_prepare_host(const char *profile_path,char *host_id,size_t hostcap,char *err,size_t errcap){static amigpt_profile p;int lr;if(!profile_path)profile_path=AMIGPT_DEFAULT_PROFILE;lr=amigpt_profile_load(profile_path,&p);if(lr<0){snprintf(err,errcap,"cannot read profile");return -1;}if(ensure_host_id(&p,err,errcap)<0)return -1;if(amigpt_profile_save(profile_path,&p)<0){snprintf(err,errcap,"cannot save profile");return -1;}if(host_id&&hostcap)snprintf(host_id,hostcap,"%s",p.host_id);return 0;}
static void apply_tokens(amigpt_profile *p,const char *client_id,const amigpt_tokens *t,const amigpt_identity *id){if(client_id&&*client_id)snprintf(p->client_id,sizeof p->client_id,"%s",client_id);snprintf(p->access_token,sizeof p->access_token,"%s",t->access_token);snprintf(p->id_token,sizeof p->id_token,"%s",t->id_token);if(t->refresh_token[0])snprintf(p->refresh_token,sizeof p->refresh_token,"%s",t->refresh_token);snprintf(p->scope,sizeof p->scope,"%s",t->scope);p->expires_in=t->expires_in;p->earliest_refresh_at=t->earliest_refresh_at;p->saved_at=(long)time(0);if(id){snprintf(p->subject,sizeof p->subject,"%s",id->subject);snprintf(p->email,sizeof p->email,"%s",id->email);}}
static void refresh_claims_from_id_token(amigpt_profile *p){static char h[2048],payload[16384],x[512];if(amigpt_jwt_decode_parts(p->id_token,h,sizeof h,payload,sizeof payload,0)<0)return;if(amigpt_json_string(payload,"chatgpt_account_id",x,sizeof x)==1)snprintf(p->account_id,sizeof p->account_id,"%s",x);if(amigpt_json_string(payload,"email",x,sizeof x)==1)snprintf(p->email,sizeof p->email,"%s",x);if(amigpt_json_string(payload,"sub",x,sizeof x)==1)snprintf(p->subject,sizeof p->subject,"%s",x);}
int amigpt_session_device_login(const char *profile_path,char *err,size_t errcap){static amigpt_profile p;static amigpt_tokens t;static char account[256],email[384];int lr;if(!profile_path)profile_path=AMIGPT_DEFAULT_PROFILE;lr=amigpt_profile_load(profile_path,&p);if(lr<0){snprintf(err,errcap,"cannot read profile");return -1;}if(ensure_host_id(&p,err,errcap)<0)return -1;if(amigpt_device_login(&t,account,sizeof account,email,sizeof email,err,errcap)<0)return -1;apply_tokens(&p,AMIGPT_CODEX_CLIENT_ID,&t,0);snprintf(p.account_id,sizeof p.account_id,"%s",account);if(email[0])snprintf(p.email,sizeof p.email,"%s",email);refresh_claims_from_id_token(&p);if(amigpt_profile_save(profile_path,&p)<0){snprintf(err,errcap,"cannot save profile");return -1;}return 0;}
int amigpt_session_login(const char *profile_path,char *err,size_t errcap){static amigpt_profile p;static amigpt_tokens t;static amigpt_identity id;static char client_id[256];int lr;if(!profile_path)profile_path=AMIGPT_DEFAULT_PROFILE;lr=amigpt_profile_load(profile_path,&p);if(lr<0){snprintf(err,errcap,"cannot read profile");return -1;}if(ensure_host_id(&p,err,errcap)<0)return -1;if(amigpt_browser_login(&p,&t,&id,client_id,sizeof client_id,err,errcap)<0)return -1;apply_tokens(&p,client_id,&t,&id);refresh_claims_from_id_token(&p);if(amigpt_profile_save(profile_path,&p)<0){snprintf(err,errcap,"cannot save profile");return -1;}return 0;}
int amigpt_session_refresh(const char *profile_path,char *err,size_t errcap){static amigpt_profile p;static amigpt_tokens t;static amigpt_identity id;if(!profile_path)profile_path=AMIGPT_DEFAULT_PROFILE;if(amigpt_profile_load(profile_path,&p)!=1){snprintf(err,errcap,"no profile; import a SIWC profile or run LOGIN");return -1;}if(!p.client_id[0]||!p.refresh_token[0]){snprintf(err,errcap,"profile has no refresh token; import a SIWC profile or run LOGIN");return -1;}if(!strcmp(p.client_id,AMIGPT_CODEX_CLIENT_ID)){if(amigpt_refresh_device_tokens(p.client_id,p.refresh_token,&t,err,errcap)<0)return -1;apply_tokens(&p,p.client_id,&t,0);refresh_claims_from_id_token(&p);}else{if(amigpt_refresh_tokens(p.client_id,p.refresh_token,&t,err,errcap)<0)return -1;if(amigpt_verify_id_token(t.id_token,p.client_id,"",&id,err,errcap)<0)return -1;apply_tokens(&p,p.client_id,&t,&id);refresh_claims_from_id_token(&p);}if(amigpt_profile_save(profile_path,&p)<0){snprintf(err,errcap,"cannot save profile");return -1;}return 0;}
int amigpt_session_load_ready(const char *profile_path,amigpt_profile *profile,char *err,size_t errcap){if(!profile_path)profile_path=AMIGPT_DEFAULT_PROFILE;if(amigpt_profile_load(profile_path,profile)!=1){snprintf(err,errcap,"no profile; import a Sign in with ChatGPT profile first");return -1;}if(!profile->client_id[0]||!profile->access_token[0]){snprintf(err,errcap,"profile has no SIWC credentials; run REFRESH or import a profile");return -1;}if(!strcmp(profile->client_id,AMIGPT_CODEX_CLIENT_ID)){snprintf(err,errcap,"legacy DEVICELOGIN profile cannot be used for MODELS/CHAT; import a SIWC profile");return -1;}if(!amigpt_scope_has(profile->scope,"chatgpt.tokens.use.direct")){snprintf(err,errcap,"profile lacks chatgpt.tokens.use.direct");return -1;}return 0;}
